# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.11

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
        args:
        -   --unsafe
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.10
    hooks:
    -   id: ruff
        exclude: migrations/
        args:
        - --fix
    -   id: ruff-format

-   repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        args:
        - --remove-all-unused-imports
        - --remove-unused-variables
        - --ignore-init-module-imports
        - --in-place
        - --recursive

-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black src/
        always_run: true
        pass_filenames: false
        language: system
        types: [python]

    -   id: isort
        name: isort
        entry: poetry run isort src/
        always_run: true
        pass_filenames: false
        language: system
        types: [python]

    -   id: mypy
        name: mypy
        entry: poetry run mypy src/
        always_run: true
        pass_filenames: false
        language: system
        types: [python]
